# Generated by Django 4.0.6 on 2022-08-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('iban', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cuenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposCuenta',
            fields=[
                ('tcu_id', models.AutoField(db_column='TCU_id', primary_key=True, serialize=False)),
                ('tcu_tipo', models.TextField(db_column='TCU_tipo', unique=True)),
            ],
            options={
                'db_table': 'Tipos_Cuenta',
                'managed': False,
            },
        ),
    ]
