# Generated by Django 4.0.6 on 2022-08-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id_movimientos', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion_mov', models.IntegerField(blank=True, null=True)),
                ('numero_cuenta', models.IntegerField(blank=True, null=True)),
                ('tp_operacion', models.CharField(blank=True, max_length=200, null=True)),
                ('hora_trans', models.IntegerField(blank=True, null=True)),
                ('new_balance', models.IntegerField(blank=True, db_column='New_balance', null=True)),
            ],
            options={
                'db_table': 'movimientos',
                'managed': False,
            },
        ),
    ]
