# Generated by Django 4.0.6 on 2022-08-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_surname', models.CharField(max_length=100)),
                ('customer_DNI', models.CharField(max_length=10)),
                ('dob', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'ordering': ['-customer_id'],
            },
        ),
    ]
