# Generated by Django 4.0.6 on 2022-08-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ['-customer_id'], 'verbose_name': 'client'},
        ),
        migrations.AlterField(
            model_name='clientes',
            name='customer_DNI',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
